version: '2'
services:
  jolokia:
    image: jolokia/java-jolokia
    volumes:
      - /opt/jolokia/

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from: 
      - jolokia

  kafka-1:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from: 
      - jolokia

  kafka-2:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from: 
      - jolokia
      
  kafka-3:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'false'
      KAFKA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from: 
      - jolokia

  telegraf-topic:
    image: confluentinc/cp-kafka:5.3.1
    command: bash -c "cub kafka-ready -z zookeeper:2181 1 30 && kafka-topics --zookeeper zookeeper:2181 --create --topic telegraf --partitions 10 --replication-factor 3"
    depends_on:
      - zookeeper

  telegraf:
    image: telegraf:1.8
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./telegraf.conf:/tmp/telegraf.conf:ro
      - ./telegraf-inputs/:/tmp/telegraf-inputs/:ro
    command: telegraf -config /tmp/telegraf.conf --config-directory /tmp/telegraf-inputs
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3

  producer:
    build: ../step3/producer
    environment:
      JAVA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from:
      - jolokia
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  consumer:
    build: ../step3/consumer
    environment:
      JAVA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from:
      - jolokia
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  streams:
    build: ../step6/streams
    environment:
      JAVA_OPTS: "-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0"
    volumes_from:
      - jolokia
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - telegraf
